### ISSUE TITLE
gcc version check in configure.ac needs to check that the compiler is gcc first

### ISSUE THREAD

**Issue by ryandesign** [mywave82/opencubicplayer#103]
During configure of ocp 0.2.105 I see:

```
checking gcc version... 13.0.0, ok
```

That's wrong. I'm not using gcc; I'm using clang.

This was previously reported in #30 which was closed as completed.

**Comment by mywave82** [comment]
The check is to stop the user from attempting to compile with compilers that are known to generate bad code etc.

I will add an explicit test to verify that the compiler is gcc before attempting to match against the versions-numbers that known bad.


`checking for gcc... clang`
For correcting this message to be more correct like `checking for CC... clang` and `checking for CC_FOR_BUILD... clang`, you have to reach out to autoconf

**Comment by ryandesign** [comment]
> I will add an explicit test to verify that the compiler is gcc before attempting to match against the versions-numbers that known bad.

Thanks! That should fix it.

> `checking for gcc... clang` For correcting this message to be more correct like `checking for CC... clang` and `checking for CC_FOR_BUILD... clang`, you have to reach out to autoconf

Yup, but I'm not concerned about that today.
