### ISSUE TITLE
X Error of failed request:  BadMatch (invalid parameter attributes)

### ISSUE THREAD

**Issue by ryandesign** [mywave82/opencubicplayer#104]
In the process of adding ocp to MacPorts, I have compiled and run it (version 0.2.105) on macOS for the first time. I opened the X11 version and it displayed its window which included at the bottom the message:

> press `F1` for help, or `ALT-C` for basic setup

I pressed `F1` and its help was displayed. It included the message:

> If you want to quit help, please use one of the keys you activate it with, `<H>`, `<?>`, or `<F1>`.

I pressed `F1` again and the program closed and I was left with this message in my terminal:

```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  6036
  Current serial number in output stream:  6036
```

**Comment by ryandesign** [comment]
The same thing happens if I just try to resize the original main window after the program opens.

**Comment by mywave82** [comment]
X11 is to my knowledge untested on MacOS, since brew uses SDL2.

Looking at the error-message it appears to not using Shm, which will be slow. I will try to investigate this before the next release.

**Comment by mywave82** [comment]
(Next release is hopefully not too far away. Need to finish the mingw and RetroWave OPL3 support)
