### ISSUE TITLE
unifont path for ubuntu

### ISSUE THREAD

**Issue by bkw777** [mywave82/opencubicplayer#106]
ubuntu:
```
$ sudo apt install fonts-unifont
$ ./configure --with-unifontdir-otf=/usr/share/fonts/opentype/unifont`
```

**Comment by mywave82** [comment]
What exactly is the problem you are trying to describe? The default path uses --datarootdir, which against defaults to using --prefix, so if you do not specify --prefix and/or --datarootdir, the default path will be
/usr/local/share/fonts/opentype/unifont

The is the expected autoconf default behaviour.

**Comment by bkw777** [comment]
Since there are some default paths that are searched, that implies there is some intended effort to have the common case work out of the box. So I was just supplying the finding that this is the out of the box path on ubuntu.

Now that you say it's because of $PREFIX, I don't recall many other times where the destination prefix is more than the first default try for sources and dependencies, not the only try.

I haven't looked yet but I can't imagine that this is just the way autoconf works, since I feel like I must have noticed that sometime in the last 30 years. But you never know.

Would you mind a pr that adds searching /usr after searching prefix if they aren't the same?

**Comment by mywave82** [comment]
I'm always open for PRs

**Comment by mywave82** [comment]
https://github.com/mywave82/opencubicplayer/commit/96286b7d75ded92da325d8aad823e1e39cf6cb60

Makes it easier to see what is going on atleast.
