### ISSUE TITLE
problems configuring 0.2.106 & libancient

### ISSUE THREAD

**Issue by tsr** [mywave82/opencubicplayer#108]
Hi all,

i just wanted to compile and upgrade to 0.2.106, then while running `./configure` i had problems with letting it detect `libancient`:
```
checking for libancient... no
configure: error: libancient not found
```

As i use Gentoo where currently there is no official package of libancient, i compiled and installed it myself with version 2.1.1 (i hope https://github.com/temisu/ancient is the correct libancient required?).
Now libancient resides in `/usr/local/lib/` (where `/usr/local/lib/libancient.a`, `/usr/local/lib/libancient.la`, `/usr/local/lib/libancient.so`, `/usr/local/lib/libancient.so.2`, `/usr/local/lib/libancient.so.2.0.1` are).

But somehow `./configure` won't detect it. Is there something i'm missing? I also already ran env-update & ldconfig to be sure. The `ancient` CLI-tool also works.

Thanks for your help!

**Comment by mywave82** [comment]
You probably need to set PKG_CONFIG_PATH, so that pkg-config can find libancient.pc

If you make an overlay to gentoo system, you should make an rebuild for both ancient and open cubic player. Many years since used Gentoo

**Comment by tsr** [comment]
Ohh thank you. PKG_CONFIG_PATH was indeed missing. Was too lazy to create ebuilds yet, because ocp didn't update that often and was fine with plain config & make. :) But i might indeed consider it, especially because of the now existing dependency.

Anyway for everyone else stumbling on this, just run the following and `./configure` of ocp should be fine:
`export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/`
(libancient.pc should be already in this path)
