### ISSUE TITLE
Some FLAC files fail to play

### ISSUE THREAD

**Issue by apollo18210** [mywave82/opencubicplayer#111]
Hello,

I wanted to report that when I try and play certain files in the FLAC format, that OCP returns an error and fails to play them.  The error that is returned is below:

> playflac: ERROR libflac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_METADATA
> [FLAC] FLAC__seekable_stream_decoder_process_until_end_of_metadata() failed
> error: file structure corrupted

I can confirm that these files play in other players.  I tried to compare the metadata in the files that play in OCP with others that don't.  The only difference I can see is that the "corrupt" files contain album art.  Maybe OCP is unable to process embedded album art in FLAC files?

I've tested this on OCP v0.2.107 (compiled from the latest master 93ec77fa19226a42972d599a2037e2b0cbd2ac00).

**Comment by mywave82** [comment]
Can you provide me with a non-working file. You can give it to me by email, Google-drive or similar means. Same goes for SPC file.

stian.skjelstad@gmail.com

**Comment by apollo18210** [comment]
Email sent with FLAC and SPC samples.
