### ISSUE TITLE
SPC files don't loop

### ISSUE THREAD

**Issue by apollo18210** [mywave82/opencubicplayer#112]
I've noticed that SPC files don't loop, even if I have playonce=off and loop=on set in the ocp.ini file.  Once the playback length is reached, playback stops.  OCP won't even advance to the next song in the playlist unless I press Enter to do so.

Other formats using libgme loop, as well as the other formats supported my OCP like modules, mp3s, flacs.

I've tested this on OCP v0.2.107 (compiled from the latest master 93ec77fa19226a42972d599a2037e2b0cbd2ac00).

**Comment by mywave82** [comment]
Root problem is that game-music-emulator library does not detect end of song for most file formats it serves, as many of them are actually binaries running on virtual machines without an interface to inform about song status.

But should be possible to detect that no audio has been detected for a given amount of time.
