### ISSUE TITLE
ocp-curses 0.2.0 crashes at 5 seconds (ahx)

### ISSUE THREAD

**Issue by alexmyczko** [mywave82/opencubicplayer#16]
with the msg:
`Division by zero / Floating Point Error`

http://bootes.ethz.ch/rubbersphinx.ahx

**Comment by mywave82** [comment]
Problem is present upstream too:
https://github.com/pete-gordon/hivelytracker/tree/master/hvl2wav
This also produces the same crash

**Comment by mywave82** [comment]
Patch commited to master and upstream. Waiting for upstream to verify fix before closing

**Comment by mywave82** [comment]
https://github.com/pete-gordon/hivelytracker/pull/38

**Comment by mywave82** [comment]
Approved upstream
