### ISSUE TITLE
building on GNU/Hurd fails (mind you hurd has no audio drivers)

### ISSUE THREAD

**Issue by alexmyczko** [mywave82/opencubicplayer#2]
build logs available at
https://buildd.debian.org/status/package.php?p=ocp&suite=sid

and Hurd, is also only 32-bit, and single core support. So not sure if you want this to fix or not.

**Comment by mywave82** [comment]
PATH_MAX will eventually be faced out from OpenCubicPlayer sources, due to it being an old relic that is not actually safe to rely on, when present

**Comment by mywave82** [comment]
Does the current git-master compile on Hurd now? I suspect it can fail to compile the timidity plugin. Maybe we can add some define-magic spesific for GNU_HURD in that case

**Comment by alexmyczko** [comment]
Yes builds now!!!
