### ISSUE TITLE
Using Jack2 as an Audio Device

### ISSUE THREAD

**Issue by Bildcraft1** [mywave82/opencubicplayer#26]
I have an Jack2 setup + Alsa + PulseAudio, how i can set Jack2 in OCP? (if it's possible of course)

**Comment by mywave82** [comment]
I have little to no experience with jack.

Isn't jack/jack2 an audio server that provides the same functionality as PulseAudio.

For ALSA, the current output device (virtual or real) can for the current session be configured in the setup: filesystem in the filebrowser, and permanent in ~/.ocp/ocp.ini

Beware, SDL2 might be your default audio driver in open cubic player, and that has limited output configuration, and mostly autoconfigures itself. 

How do you configure in jack2 in most other generic ALSA or SDL2 applications?

**Comment by Bildcraft1** [comment]
So i have Cadence, wich Is a set of tools useful for audio production, i have setupped Jack2 that have a bridge with ALSA
The bridge Is like this:
ALSA -> PulseAudio -> Jack2
So ALSA Is the main Audio Server

**Comment by mywave82** [comment]
If JACK2 and JACK has the same API, it should work already using SDL2 for audio in OCP

**Comment by mywave82** [comment]
Alsa has jack plugin removing the need for dedicated JACK audio driver which can be selected in the ALSA audio driver.

If anybody want to make a dedicated jack audio plugin, patches are welcome
