### ISSUE TITLE
gcc version requirements

### ISSUE THREAD

**Issue by bluewww** [mywave82/opencubicplayer#3]
During the configure step I get the following error:
`checking gcc version... configure: error: 9.1.0, bad`
Which gcc versions are supported?

**Comment by mywave82** [comment]
I just added gcc 9 and 10 to the configure.ac known-good-list in the git-repo.

Some of the stone old versions of gcc had some wierd bugs (and people still compile OCP on wierd ancient devices)

**Comment by bluewww** [comment]
ok thanks that works for me
