### ISSUE TITLE
Fragile gcc version check

### ISSUE THREAD

**Issue by mitchblank** [mywave82/opencubicplayer#30]
From configure.in:
```
cc_version=`( $CC -dumpversion ) 2>&1`
[...]
	case $cc_version in
[...]
		2.95.[[2-9]]|2.95.[[2-9]][[-]].*|3.[[0-9]]|3.[[0-9]].[[0-9]]|3.[[0-9]]|3.[[0-9]].[[0-9]]-*|4.*|5.*|6.*|7*|8*|9*|10*)
			_cc_major=`echo $cc_version | cut -d '.' -f 1`
			_cc_minor=`echo $cc_version | cut -d '.' -f 2`
			_cc_mini=`echo $cc_version | cut -d '.' -f 3`
			if test $_cc_major -gt 2; then
				AC_MSG_RESULT([$cc_version, ok])
			else
				AC_MSG_ERROR([$cc_version, bad])
			fi
```

First, I doubt tat anyone is trying to compile with gcc-2.7.2 any more, so I doubt this check serves a purpose.

Second, gcc 11 is right around the corner and will break with this check

Third, if another gcc-like compiler gets detected the version is meaningless.  I tripped over this building with Xcode 12 (i.e. clang) and it reported "12.0" making `./configure` fail

**Comment by mywave82** [comment]
Yes, it should be rewritten to ignore anything except the known bad versions. But old gcc versions still appear when people compile this thing on strange things like old nokia phones.

**Comment by alexmyczko** [comment]
Trying to build on my MBA space gray: `Darwin peach.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64`

./configure part goes fine.
`CC=/opt/homebrew/bin/gcc-10 ./configure --with-unifontdir=/Users/alex/Library/Fonts/ --without-desktop_file_install`

but `make` fails with:
```
/opt/homebrew/bin/gcc-10 -g -O2 -fno-common -fPIC -Wall -I.././ cpiscope.c -o cpiscope.o -c
/var/folders/zs/rx_3t0h11j90z5_mr8x_3dy00000gn/T//cc5Ps2PL.s:3413:20: error: expected 'sxtx' 'uxtx' or 'lsl' with optional integer in range [0, 4]
        add     x20, x2, x20, uxtw 1
                              ^
make[1]: *** [cpiscope.o] Error 1
make: *** [dirs] Error 2
```
