### ISSUE TITLE
Division by zero error when playing ogg vorbis files

### ISSUE THREAD

**Issue by WildPenquin** [mywave82/opencubicplayer#34]
Hi,

I get a division by zero error when playing ~most (but not all) of my~ any ogg vorbis files.

I can reproduce this on two computers; first one running Arch Linux (Zen5) and the other running Gentoo (i486!).

I can provide debug logs etc., unless you can easily reproduce this. If you can not, one culprit could be tags in the ogg files. I've tagged my collection with MusicBrainz (which means, the tags will be very detailed and elaborate on average).

**EDIT:** This on 0.2.90. Also, conversely to what I've claimed above, I can **not play** and ogg vorbis files currently. Case may be, my collection is quite large and I've forgotten which ogg files I was able to play, and can not find them anymore ... or, I may have been playing some other files.

**Comment by mywave82** [comment]
Hi

Can you please share one of the files with me privatly per email on stian.skjeltad@gmail.com ?

**Comment by WildPenquin** [comment]
Hi,

For example this file causes a division by zero here: [https://commons.wikimedia.org/wiki/File:Example.ogg](example file from wikimedia.org)

Indeed, I can not play **any** ogg vorbis file currently with ocp. I probably just though I was playing an ogg vorbis file, when I wasn't; I have some mp3 and flac mixed inside my collection, and those play without any problems (*).

*) well, actually mp3 files cause some error messages along the lines: 
`wanted to read 39695 bytes, and got 39695 bytes`
which is a bit annoying especially if running in text mode (it causes other elements of the display/player to be displaced as they are printed over the spectrum analyzer etc.). But that is a separate issue. The actual playback of mp3 sound fine despite the error messages.

**Comment by WildPenquin** [comment]
`Setting to cfConfigDir to /home/ville/.ocp/
Setting to cfDataDir to /usr/share/ocp-0.2.90/data/
Setting to cfProgramDir to /usr/lib/ocp-0.2.90/
Open Cubic Player for Unix v0.2.90, compiled on Jun 27 2021, 21:12:07
Ported to Unix by Stian Skjelstad
linking default objects...
running initializers...
initializing fileselector...
adbMetaInit: open(cfConfigDir/CPARCMETA.DAT): No such file or directory
Loading /home/ville/.ocp/CPMODNFO.DAT .. Done
open(cfConfigDir/CPDIRDB.DAT): No such file or directory
Initing console...
stdout and stdin does not come from the same device, trying X11
[x11] X is online
[x11] rootwindow: width:3440 height:1440
[x11] xvidmode disabled in ocp.ini
Locating cdroms [.....]
wavetabledevices:
 devwMixF: FPU Mixer....................... (#1 t0)
 devwmixQ: Mixer........................... (#2 t1)
 devwMix : Mixer........................... (#3 t0)
 devwNone: None............................ (#4)
FPU Mixer selected...
[devwmixf] INIT, using dwmixfa.c C version

playerdevices:
 devpALSA: ALSA device driver.............. (#1)
 devpOSS : OSS player...................... not found: optimize ocp.ini!
 devpCA  : /usr/lib/ocp-0.2.90/devpcoreaudio.so: cannot open shared object file: No such file or directory
link error
 devpSDL2: SDL2 Player..................... (#3 p0 q0)
 devpSDL : /usr/lib/ocp-0.2.90/devpsdl.so: cannot open shared object file: No such file or directory
link error
 devpNone: Super High Quality Quiet Player. (#4)
 devpDisk: Disk Writer..................... (#5)
ALSA device driver selected...

samplerdevices:
 devsOSS : OSS Recorder.................... not found: optimize ocp.ini!
 devsNone: Eternal Silence Recorder........ (#2)
Eternal Silence Recorder selected...

   unix_dir_readdir_file "/home/ville/Roskia/Example.ogg"
   unix_file_steal => 0x5625e80c1490
loading Example .ogg...
^[[H^[[2J^[[3JDivision by zero / Floating Point Error
`

**Comment by mywave82** [comment]
I have located the problem. ov_open_callbacks() has changed slightly behaviour in libvorbisfile. I will add update to OCP to compensate
