### ISSUE TITLE
https://play.cubic.org/?f=https://mysite.com/mymodule.xm

### ISSUE THREAD

**Issue by coderofsalvation** [mywave82/opencubicplayer#35]
Anyone ever tinkered with the idea to compile ocp to javascript using emscripten?
I've discovered [chip-player-js](https://mmontag.github.io/chip-player-js), however it doesn't allow playing (remote) files
In theory, if ocp is SDL-compatible, emscripten could compile it to JS and access local directory(s) using https://www.npmjs.com/package/browser-fs-access, or maybe just browse thru module-repositories like https://www.stef.be/bassoontracker/.

> On top of that (and to get back to the subject), OCP could make a cool online (and embeddable) player for the web.

**Comment by mywave82** [comment]
An effort would be needed to make ocp not depend on the use of plugins. This is a trait of the original code-base being as restricted on memory as possible. Volunteers cant of experiment with these kinds of things. I'm currently looking into another rabbit-hole that was way deeper than expected, so have been some time since my last commit.

**Comment by coderofsalvation** [comment]
Apoligies for my ignorance, but plugins in what?
On ubuntu I can just apt-get ocp, and then it magically works  (without me having to install plugins e.g.)
Do you mean dynamic libraries (which are called plugins in cubic world?).

**Comment by mywave82** [comment]
Ubuntu package ships all the plugins bundled in the ocp package, and they are stored as dynamic libraries.

**Comment by coderofsalvation** [comment]
Interesting.
I will close this issue for now, as it is not a bug or something.

Anyways big thanks for developing this project further.
OCP is something more than just a musicplayer, I can't really pinpoint the unique selling point though.
Maybe it's more something like a realtime music inspector / entertainment player-environment.
It's like listening to music AND poking around at the same time.
