### ISSUE TITLE
Fail during run ./configure

### ISSUE THREAD

**Issue by kpstsp** [mywave82/opencubicplayer#53]
I try to make ocp from sources. 
When i run ./configure it ask me get submodules:

`checking GIT submodules are checked out... configure: error: playtimidity/timidity-git is missing - please execute 'git submodule update --init --recursive'`

Next when i run submodule update commands:

`Submodule 'src/builders/resid-builder/resid' (https://github.com/mywave82/resid.git) registered for path 'playsid/libsidplayfp-git/src/builders/resid-builder/resid'
Cloning into '/home/trx/tmp/opencubicplayer/playsid/libsidplayfp-git/src/builders/exsid-builder/driver'...
Cloning into '/home/trx/tmp/opencubicplayer/playsid/libsidplayfp-git/src/builders/resid-builder/resid'...
Submodule path 'playsid/libsidplayfp-git/src/builders/exsid-builder/driver': checked out '9d8b572b92089912a95f67fb1c42892a2e69096e'
fatal: remote error: upload-pack: not our ref c94fcf9161fb72a1b8f89eee7870069d65504fba
Fetched in submodule path 'playsid/libsidplayfp-git/src/builders/resid-builder/resid', but it did not contain c94fcf9161fb72a1b8f89eee7870069d65504fba. Direct fetching of that commit failed.
Submodule path 'playtimidity/timidity-git': checked out '77cd92db7251393959be71af3d065949847bbdf9'
Failed to recurse into submodule path 'playsid/libsidplayfp-git'`

OS: Antix, based on Debian GNU/Linux 11 (bullseye)

**Comment by mywave82** [comment]
Please try now :-) I seems that I missed to push a sub-sub-module

**Comment by kpstsp** [comment]
Thanks! It works
