### ISSUE TITLE
Ocp crashes on getting titles of songs in directory

### ISSUE THREAD

**Issue by sneakernets** [mywave82/opencubicplayer#58]
revision [d497484](https://github.com/mywave82/opencubicplayer/commit/d497484014f709c519aaf50c56580729d07a9e4d)

error:
```
dirdbGetName_internalstr: invalid node #1
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_M_construct null not valid
Aborted.
```

Compiling this on a Raspberry Pi with the latest Legacy OS, gcc 8. Seems to be a recent issue! I have used the git repo code for months now, so I do know it has compiled and ran on here in the past.

**Comment by mywave82** [comment]
Hi

Are you able to isolate a single file from that directory that triggers the crash? (Try to copy some files at a time into a test directory)

Stian

**Comment by sneakernets** [comment]
I did some tests with a clean folder with a midi file and  got a crash. I know that's not helpful, but it isn't due to any malformed files as far as I can tell. I have cleaned the project, reconfigured and rebuilt and still getting the same behavior.

**Comment by mywave82** [comment]
Can you try to wipe the installed files. Some plugins have been merged and others had name changed. They are probably located in /usr/local/lib/ocp/ and /usr/local/lib/ocp/autoload/

**Comment by sneakernets** [comment]
Sure! That fixed the issues too! thank you so much!
