### ISSUE TITLE
ocp does not close after typing Ctrl-C into the terminal or clicking the close box once on the UI window

### ISSUE THREAD

**Issue by cranderson** [mywave82/opencubicplayer#62]
Typing Ctrl-C in the terminal window where ocp was launched from or clicking the close box once on the UI window doesn't close ocp.  Ctrl-C seems to print a register dump and reopens the UI windows no matter how many times you type it.  It might be nice to kill ocp after the 2nd or subsequent Ctrl-C.  This would be especially helpful if ocp hangs for whatever reason.

While a file is playing, the Window Close box closes only on the 2nd click--the 1st click turns the top bar red, like Esc key does, then the 2nd click closes normally.  The Esc key behavior makes sense and is how ocp has always worked in the DOS days etc.  But I wonder if the graphical UI shouldn't behave that way--perhaps Close should always close on the 1st click like all other GUI programs work.

See also https://bugzilla.redhat.com/show_bug.cgi?id=2086433

**Comment by mywave82** [comment]
Ctrl-C is now fixed.

The close-on pressing X on the window is more tricky. Open Cubic Player does not have a universal exit-path, and depending on where in the dialogs, it varies how many <esc> key presses that might be needed to emulate in order to simulate a clean quit.

**Comment by mywave82** [comment]
I agree that X on the window should close the program, not insert a single <esc> key
