### ISSUE TITLE
BUG in hvl play since commit #99eda882c4876454d1e17721424357f39784556e

### ISSUE THREAD

**Issue by cysp74** [mywave82/opencubicplayer#67]
Hi,

Another bug cropped up since mentioned commit in subject.
Ocp can play only one ahx/hvl file, but the second can't be started by the same process, exit/start is necessary.

Easy to reproduce, start ocp, play ahx, and try play another or same ahx again.

**Comment by mywave82** [comment]
Thank you for testing the master branch. I'm the in process of some major internal changes and things like this can appear. I will probably fix this issue during this week after I finish another big internal change.

**Comment by mywave82** [comment]
I am unable to reproduce. Does the current master still have this issue, and can you ensure that the old installation is not present. Some .so files have been renamed and others removed.

If still present, which compiler variant/version are you using, maybe there is some quirk that triggers the issue.

**Comment by cysp74** [comment]
I cleaned out previous build directory and hit a fresh build w/ latest commit (80b8cef35faf718ad51b005ab29d0cf6404f4b1b).
Checked if uninstalling of previous binary left any artifact, found nothing. Afterwards I deleted ocp.dat. 

So I played eg. (as log shows below) "Rainmaking" ahx from JazzCat.
__Waited till ended and tried to restart__.
This is quite important to face the bug (revealed during this iteration)
When if I tried to restart the song, or choose other ahx during an AHX playing, player was able to play the next song.

(Arch based linux box):
GCC version: gcc (GCC) 12.2.0
g++ (symlink ofcoz, just wanted to be diligent): g++ (GCC) 12.2.0
binutils: 2.39

Build options are:
--prefix=/usr --sysconfdir=/etc --with-timidity-default-path=/etc/timidity++/ --without-x11 --without-sdl --without-sdl2 --with-ncurses --without-debug


Stdout of ocp is below:
Creating /xxx/xxx/.ocp/
/xxx/xxx/.ocp/ocp.ini created
Setting to cfConfigDir to /xxx/xxx/.ocp/
Setting to cfDataDir to /usr/share/ocp/data/
Setting to cfProgramDir to /usr/lib/ocp/
Open Cubic Player for Unix v0.2.99, compiled on Sep 20 2022, 13:05:07
Ported to Unix by Stian Skjelstad
linking default objects...
running initializers...
initializing fileselector...
adbMetaInit: open(cfConfigDir/CPARCMETA.DAT): No such file or directory
Loading /home/home/.ocp/CPMODNFO.DAT .. No header
open(cfConfigDir/CPDIRDB.DAT): No such file or directory
Loading /home/home/.ocp/CPMUSBRN.DAT .. Empty database
Initing console... 
We have a PTY (so no need to test for framebuffer and/or vcsa)
Initing curses... (ncurses 6.3.20211021)
curses: will use UTF-8 characters instead of ASCII + ACS
Locating cdroms [.....]
playerdevices:
 devpALSA: ALSA device driver.............. (#1)
 devpOSS : OSS player...................... not found: optimize ocp.ini!
 devpCA  : /usr/lib/ocp/devpcoreaudio.so: cannot open shared object file: No such file or directory
link error
 devpSDL2: /usr/lib/ocp/devpsdl2.so: cannot open shared object file: No such file or directory
link error
 devpSDL : /usr/lib/ocp/devpsdl.so: cannot open shared object file: No such file or directory
link error
 devpNone: Super High Quality Quiet Player. (#3)
 devpDisk: Disk Writer..................... (#4)
ALSA device driver selected...

wavetabledevices:
 devwMixF: FPU Mixer....................... (#1 t0)
 devwmixQ: Mixer........................... (#2 t1)
 devwMix : Mixer........................... (#3 t0)
 devwNone: None............................ (#4)
FPU Mixer selected...
[devwmixf] INIT, using dwmixfa.c C version

loading JazzCat - Rainmaking - rainmaking.ahx (7050 bytes)...
loading JazzCat - Rainmaking - rainmaking.ahx (7050 bytes)...
loading JazzCat - Rainmaking - rainmaking.ahx (7050 bytes)...
loading JazzCat - Rainmaking - rainmaking.ahx (7050 bytes)...


Pls let me know if i missed something out and need more info.

**Comment by cysp74** [comment]
Sorry my previous comment had some sensitive info. :)

I cleaned out previous build directory and hit a fresh build w/ latest commit (https://github.com/mywave82/opencubicplayer/commit/80b8cef35faf718ad51b005ab29d0cf6404f4b1b).
Checked if uninstalling of previous binary left any artifact, found nothing. Afterwards I deleted ocp.dat.

So I played eg. (as log shows below) "Rainmaking" ahx from JazzCat.
__Waited till ended and tried to restart.__
This is quite important to face the bug (revealed during this iteration)
When if I tried to restart the song, or choose other ahx during an AHX playing, player was able to play the next song.

(Arch based linux box):
GCC version: gcc (GCC) 12.2.0
g++ (symlink ofcoz, just wanted to be diligent): g++ (GCC) 12.2.0
binutils: 2.39

Build options are:
--prefix=/usr --sysconfdir=/etc --with-timidity-default-path=/etc/timidity++/ --without-x11 --without-sdl --without-sdl2 --with-ncurses --without-debug

Stdout of ocp is below:
Creating /xxx/xxx/.ocp/
/xxx/xxx/.ocp/ocp.ini created
Setting to cfConfigDir to /xxx/xxx/.ocp/
Setting to cfDataDir to /usr/share/ocp/data/
Setting to cfProgramDir to /usr/lib/ocp/
Open Cubic Player for Unix v0.2.99, compiled on Sep 20 2022, 13:05:07
Ported to Unix by Stian Skjelstad
linking default objects...
running initializers...
initializing fileselector...
adbMetaInit: open(cfConfigDir/CPARCMETA.DAT): No such file or directory
Loading /xxx/xxx/.ocp/CPMODNFO.DAT .. No header
open(cfConfigDir/CPDIRDB.DAT): No such file or directory
Loading /xxx/xxx/.ocp/CPMUSBRN.DAT .. Empty database
Initing console...
We have a PTY (so no need to test for framebuffer and/or vcsa)
Initing curses... (ncurses 6.3.20211021)
curses: will use UTF-8 characters instead of ASCII + ACS
Locating cdroms [.....]
playerdevices:
devpALSA: ALSA device driver.............. (https://github.com/mywave82/opencubicplayer/pull/1)
devpOSS : OSS player...................... not found: optimize ocp.ini!
devpCA : /usr/lib/ocp/devpcoreaudio.so: cannot open shared object file: No such file or directory
link error
devpSDL2: /usr/lib/ocp/devpsdl2.so: cannot open shared object file: No such file or directory
link error
devpSDL : /usr/lib/ocp/devpsdl.so: cannot open shared object file: No such file or directory
link error
devpNone: Super High Quality Quiet Player. (https://github.com/mywave82/opencubicplayer/issues/3)
devpDisk: Disk Writer..................... (https://github.com/mywave82/opencubicplayer/issues/4)
ALSA device driver selected...

wavetabledevices:
devwMixF: FPU Mixer....................... (https://github.com/mywave82/opencubicplayer/pull/1 t0)
devwmixQ: Mixer........................... (https://github.com/mywave82/opencubicplayer/issues/2 t1)
devwMix : Mixer........................... (https://github.com/mywave82/opencubicplayer/issues/3 t0)
devwNone: None............................ (https://github.com/mywave82/opencubicplayer/issues/4)
FPU Mixer selected...
[devwmixf] INIT, using dwmixfa.c C version

loading JazzCat - Rainmaking - rainmaking.ahx (7050 bytes)...
loading JazzCat - Rainmaking - rainmaking.ahx (7050 bytes)...
loading JazzCat - Rainmaking - rainmaking.ahx (7050 bytes)...
loading JazzCat - Rainmaking - rainmaking.ahx (7050 bytes)...

Pls let me know if i missed something out and need more info.

**Comment by mywave82** [comment]
Thank you for the crucial detail
