### ISSUE TITLE
http/ftp modland.com 

### ISSUE THREAD

**Issue by coderofsalvation** [mywave82/opencubicplayer#74]
foobar2000 allows entering 'https://modland.com'  as a drive (it just treats the links as a filesystem).
Any idea about the easiest way to mount 'ftp://modland.com' as a drive on linux?
Together with ocp it would make module discovery much easier (you could simply create playlists from terabytes of modules without actually having to download them)

> UPDATE: https://rclone.org/overview seems to support http/ftp mounts. I will try it and close this issue after documenting my findings.

**Comment by coderofsalvation** [comment]
update: turns out it's supereasy:

```
$ apt-get install rclone    # change this to your distro install cmd
$ rclone config
n 
name> modland.com
type of storage> 33
url> https://modland.com
Edit advanced config? (y/n) y
headers> <enter>
no_head> true
q

$ rclone mount modland:/pub ~/modland.com --daemon
$ cd ~/modland.com
$ ocp
```

Everything almost works as expected..browsing files/folders...except when trying to play them:

```
mload.c: warning, fread failed #5.1
xmload.c: Warning, ins1.size<4
loading dead flower (rev.2).xm (0k)...
xmload.c: fread() failed #7
error: generic error
```

However, if I copy a file to /tmp (using cp) then it doesn play.
Is there perhaps some routine in `xmload.c` which does not respect reading from a network drive?

**Comment by mywave82** [comment]
This idea is already in my head, but it is not on the top of my TODO list. Both generic http support and modland specific support using the zip file in the webroot as a cache index for expected filenames that exists.

**Comment by coderofsalvation** [comment]
thanks for your reply.
Well in the meantime rclone does the job as well.
