### ISSUE TITLE
.kar support

### ISSUE THREAD

**Issue by redbug26** [mywave82/opencubicplayer#75]
Could you add .kar support in timidity ?
.kar file are just midi file with lyricis.. Timidity could read it without modificiation.
Thanks

**Comment by mywave82** [comment]
Can you provide me some sample files that I can test, just to ensure that detection etc. works as expected? You can send these to stian.skjelstad@gmail.com if you do not want the files to be public.

**Comment by mywave82** [comment]
Thank you. I can see that the files are regular MIDI files, but they do have additional meta data available + the lyrics. I will try to add the support for meta data as I add support for the .KAR file ending - but it might take some time. November is quite a busy month for me

**Comment by redbug26** [comment]
You was fast ! Thanks a lot

**Comment by mywave82** [comment]
Now the karaoke text is even displayed. The timidity code needed a minor change so submodules needs to be up-to-date - or do a full clean clone of the ocp project if you are unsure :-)
