### ISSUE TITLE
Can't play mid file (no sound, no visual)

### ISSUE THREAD

**Issue by criticalsoft** [mywave82/opencubicplayer#81]

**Comment by mywave82** [comment]
You need to have a soundfont installed in your system (or timidity configured). If you use ubunu there are some packages available like:
* fluid-soundfont-gm
* musescore-general-soundfont-lossless
* timgm6mb-soundfont

To select which soundfont to use, you can find a setup dialog inside the setup: filesystem.

**Comment by mywave82** [comment]
(or you can change the filetype to OPL, the adplug OPL3 engine has support for MIDI too, pressing ALT-E in the filebrowser lets you edit metadata for a given song)

**Comment by mywave82** [comment]
If you want to change soundfont, in the filebrowser, at the bottom you can find **setup:**. Open it and you should be able to locate **timidityconfig.dev**

Changes performed will be stored in **~/.ocp/ocp.ini**

**Comment by mywave82** [comment]
Midi files does not display track information, maybe I am able to make something in the future.

Alt + K brings up keyboard overview, which is context aware
