### ISSUE TITLE
Has error when compile (unifont filename) & run (permission error)

### ISSUE THREAD

**Issue by criticalsoft** [mywave82/opencubicplayer#82]

**Comment by mywave82** [comment]
Can you please provide some console output?

I am guessing that ./configure fails with that it is unable to find unifont. If you use Ubuntu atleast, this is example configure flags (assuming that _fonts-unifont_ package is installed)
`./configure --with-unifontdir-ttf=/usr/share/fonts/truetype/unifont --with-unifontdir-otf=/usr/share/fonts/opentype/unifont`

**Comment by mywave82** [comment]
For the font files, you can specify each ones exact name instead of giving the directory if your OS uses non-standard name/casing.

Can you provide console output from your command-prompt of the failures?
