### ISSUE TITLE
Can't find a way to change global volume

### ISSUE THREAD

**Issue by criticalsoft** [mywave82/opencubicplayer#87]
Shortcut key for 70% keyboard
which without (Fn+) PageUp PageDown Home End key.

**Comment by mywave82** [comment]
Are you unable to use the F2 and F3 keys?

Is this a problem for you in all console drivers, or just one of them?

Please test:
ocp-curses
ocp-sdl            (do you have SDL version compiled?)
ocp-x11           (do you have x11 version compiled?)

**Comment by alexmyczko** [comment]
alsop pressing `-` or `+` slowsly de/increases volume

**Comment by mywave82** [comment]
Please suggest alternative keys if there are keys that are not available. Keep in mind that only keys that are available internationally are a..z, 0-9, F1-F12, and the navigation keys + num-pad.

<, . ' | etc keys are different around in the world but after I added UTF-8 lookups in X11 and SDL they work again!

In the console, many of the ALT and CTRL combinations are non-good
In GUI, many of the ALT and CTRL combinations can be user-specific
