### ISSUE TITLE
insttype settings in ocp.ini doesn't work after upgrade to v0.2.102

### ISSUE THREAD

**Issue by hjerning** [mywave82/opencubicplayer#94]
There is a regression in v0.2.102 were the different insttype settings in ocp.ini makes no difference as mentioned in https://github.com/mywave82/opencubicplayer/pull/93, the instruments are now always hidden by default.

**Comment by mywave82** [comment]
Fixed by 22af4b8b59b18f2c3aff4d3e39b930af5568ee23

**Comment by hjerning** [comment]
I have verified that it works flawlessly with X11 and curses now, the behavior is partly still there for SDL2 though.
When launching `ocp-sdl2 <modulename>` both the instruments **_and_** **peak power levels** are hidden. When launching the SDL2 version without any file names it works as expected.

**Comment by mywave82** [comment]
I just retested `ocp-curses`, `ocp-x11` and `ocp-sdl2` with filename from the commandline.

```
[screen]
 mvoltype=1
 insttype=2
```
OK



```
[screen]
 mvoltype=2
 insttype=2
```
only ok if curses and the initial window is wider than 128



I assume the problem is when you set mvoltype=2 ?

**Comment by hjerning** [comment]
> I assume the problem is when you set mvoltype=2 ?
Yes with `mvoltype=2` and `insttype=3` it's OK with curses and X11 if initial window is wider than 128, with SDL2 they are hidden for me. This is maybe totally unrelated though and based on how SDL2 detects the initial resolution.

**Comment by mywave82** [comment]
Can you retest the latest master? It includes 5a57ff3d904757a34c8b568048f8192722683e14

If run ocp once, it will update ocp.ini. Afterward you can edit ocp.ini and test out the new options.

**Comment by hjerning** [comment]
Yes, now `mvoltype=2` and `insttype=3` works with `ocp-sdl2 <modulename>` too!
As a bonus `screentype` now also works as I expected it to do.

I had to remove `ocp.ini` though, otherwise I just got a segmentation fault (both with epoch 20230211 and 20221228).

**Comment by hjerning** [comment]
With https://github.com/mywave82/opencubicplayer/commit/c7fe08c614534f1f49491f476283d52e44596871 everything is solved.
