### ISSUE TITLE
Prebuild windows os 32/64 bit

### ISSUE THREAD

**Issue by Speedvicio** [mywave82/opencubicplayer#99]
This is one of the best players on linux. I wanted to know if in the future there will be the possibility of being able to have a version compatible with Windows OS.

Thank you for your hard work.

**Comment by mywave82** [comment]
I have startet on the work, see the mingw branch. This is a work in progress that does not compile yet, need to adress all the details that makes Windows a unique target

**Comment by Speedvicio** [comment]
This is great news!
Thank you :-)

**Comment by mywave82** [comment]
win32 and win64 precompiled binaries are attached to the release (beta)

**Comment by Speedvicio** [comment]
thx all seem work good, the only "bug" i have encountered is the auto creation of ocp.ini, the user need to copy paste this file from etc folder to root folder.

**Comment by mywave82** [comment]
I assume the problem you mentioned is fixed by a94927c08155233be6856d82eb9ee786ee0fe5f5, and the .zip files I have manually updated to a working state.
